version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        environment:
            DB_HOST: postgresql-store.alwaysdata.net
            DB_PORT: 5432
            DB_PASSWORD: mo50z60x
            DB_USER: store
            DB_NAME: store_db
            DB_SSLMODE: disable
        networks:
            - myevershop
        depends_on:
            - database
        ports:
            - 3000:3000

        #The postgres database:
        database:
            image: postgres:16
            restart: unless-stopped
            volumes:
                - postgres-data:/var/lib/postgresql/data
            environment:
                POSTGRES_PASSWORD: postgres
                POSTGRES_USER: postgres
                POSTGRES_DB: postgres
            ports:
                - "5432:5432"
            networks:
                - myevershop

networks:
    myevershop:
        name: MyEverShop
        driver: bridge

volumes:
    postgres-data:
